---
title: "How to Get Album Lyrics from Genius.com"
author: "Jeremy Diaz"
date: "July 27, 2017"
output: html_document
---

### Packages Used

```{r setup, message = FALSE}



# Packages used
library(rvest)
library(dplyr)



````

### Getting and Processing the Tracklist
#### From Wikipedia

```{r wiki-tracklist}



# Wikipedia page to get tracklist from
acid_rap_wiki <- "https://en.wikipedia.org/wiki/Acid_Rap"


# Get tracklist
acid_rap_tracklist <- read_html(acid_rap_wiki) %>%         # Read page
  html_nodes(".tracklist") %>%                             # Used "selectorgadget chrome extension" to know this
  html_table(fill = TRUE, header = 1) %>%                  # Turn it into a table in R
  as.data.frame() %>%                                      # Convert that to data.frame
  .[1:13, ]                                                # Only songs, not total length


# Keep only the titles
acid_rap_tracklist <- dplyr::select(acid_rap_tracklist,
                                    Title)


# Remove parentheses and stuff inside them  
acid_rap_tracklist$Title <- gsub("\\s*\\([^\\)]+\\)", "", acid_rap_tracklist$Title)


# Remove the quotation marks
acid_rap_tracklist$Title <- gsub("\"", "", acid_rap_tracklist$Title)


# Remove the forward slash in "Pusha Man / Paranoia"
acid_rap_tracklist$Title <- gsub("/", "", acid_rap_tracklist$Title)


# Remove the double space introduced by removing the forward slash
# Also replace all spaces with hyphens
acid_rap_tracklist$Title <- gsub("\\s+", "-", acid_rap_tracklist$Title)


# Remove apostrophes and make it all lower case
acid_rap_tracklist$Title <- gsub("'", "", acid_rap_tracklist$Title) %>%
  tolower()


# Complete the genius.com url ending
acid_rap_tracklist$Title <- paste0(acid_rap_tracklist$Title, "-lyrics")


# Complete the entire URL
genius_urls <- paste0("https://genius.com/Chance-the-rapper-", 
                      acid_rap_tracklist$Title)

# Check it
genius_urls


# Messed up two URLs because they're not the same format as the other pages
genius_urls[7] <- "https://genius.com/Chance-the-rapper-interlude-thats-love-lyrics"
genius_urls[13] <- "https://genius.com/Chance-the-rapper-everythings-good-good-ass-outro-lyrics"
# I knew to fix these because the for lop (2 comments down) through an error
# I then checked the "lyrics" vector to see how far the loop made it
# (how far it made it) + 1 = the track # of the URL that it messed up



```

### Downloading the Lyrics
#### From Genius

```{r genius-lyrics}



# Make empty vector to fill
lyrics <- c()


# Get lyrics via for loop
for (i in 1:13) {
  
  # Get page lyrics
  intermediate <- read_html(genius_urls[i]) %>%
    html_nodes("p") %>%
    html_text() %>%
    .[1]
  
  # Add that onto the empty vector
  lyrics <- append(lyrics, intermediate)
  
}


# Preview - the lyrics of the first song
# Which still contains song information
lyrics[1]



```

